baseURL = "https://southgateai.netlify.app/"
languageCode = "en-us"
title = "The Unfinishable Map"

# Content directory
contentDir = "content"

# Build settings
buildDrafts = false
buildFuture = false

# Disable default taxonomies (using regular sections instead)
[taxonomies]

# Markup settings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Params
[params]
  description = "An opinionated resource about philosophy and the meaning of life"
  author = "SouthgateAI"

  # Authorship display
  showAuthorship = true

# Menu
[menu]
  [[menu.main]]
    name = "Topics"
    url = "/topics/"
    weight = 1
  [[menu.main]]
    name = "Concepts"
    url = "/concepts/"
    weight = 2
  [[menu.main]]
    name = "Project"
    url = "/project/"
    weight = 3
  [[menu.main]]
    name = "Tenets"
    url = "/tenets/"
    weight = 4
